# Generated by Django 5.0 on 2024-01-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'rooms', 'verbose_name_plural': 'rooms'},
        ),
    ]
