# Generated by Django 5.0 on 2024-01-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_rooms_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
