# Generated by Django 5.0 on 2024-01-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='num_of_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
