# Generated by Django 5.0 on 2024-01-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(blank=True, default='properties/default.png', null=True, upload_to='properties/'),
        ),
    ]
